#!/bin/sh

[ "$ACTION" = ifup ] || [ "$ACTION" = ifdown ] || exit 0
[ "$INTERFACE" = wan ] || exit 0

logger -t sitepi "Network $INTERFACE $ACTION, restarting SitePi instances..."

# Get all enabled networks
enabled_networks=""
config_load 'sitepi'

config_get_bool global_enabled 'global' 'enabled' '0'
[ "$global_enabled" = "1" ] || exit 0

config_foreach get_enabled_networks 'network'

get_enabled_networks() {
    local cfg="$1"
    local enabled name
    
    config_get_bool enabled "$cfg" 'enabled' '0'
    [ "$enabled" = "1" ] || return 0
    
    config_get name "$cfg" 'name'
    [ -n "$name" ] || return 0
    
    enabled_networks="$enabled_networks $name"
}

if [ -n "$enabled_networks" ]; then
    case "$ACTION" in
        ifup)
            # Restart service when network is up
            /etc/init.d/sitepi restart
            ;;
        ifdown)
            # Stop service when network is down
            /etc/init.d/sitepi stop
            ;;
    esac
fi 