#!/bin/sh

[ "$ACTION" = ifup ] || [ "$ACTION" = ifdown ] || exit 0
[ "$INTERFACE" = wan ] || exit 0

logger -t sitepi "Network $INTERFACE $ACTION, restarting SitePi instances..."

# 获取所有启用的实例
enabled_instances=""
config_load 'sitepi'

config_get_bool global_enabled 'global' 'enabled' '0'
[ "$global_enabled" = "1" ] || exit 0

config_foreach get_enabled_instances 'instance'

get_enabled_instances() {
    local cfg="$1"
    local enabled name
    
    config_get_bool enabled "$cfg" 'enabled' '0'
    [ "$enabled" = "1" ] || return 0
    
    config_get name "$cfg" 'name'
    [ -n "$name" ] || return 0
    
    enabled_instances="$enabled_instances $name"
}

if [ -n "$enabled_instances" ]; then
    case "$ACTION" in
        ifup)
            # 网络恢复时重启服务
            /etc/init.d/sitepi restart
            ;;
        ifdown)
            # 网络断开时停止服务
            /etc/init.d/sitepi stop
            ;;
    esac
fi 