include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SitePi SDWAN
LUCI_DEPENDS:=+luci-base +sitepi
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-sitepi
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

PKG_MAINTAINER:=SitePi Team
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature 